# Generated by Django 2.2 on 2019-08-24 15:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_food', to='utils.Tag')),
            ],
            options={
                'db_table': 'foods',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('foods', models.ManyToManyField(related_name='food_meals', to='meals.Food')),
            ],
            options={
                'db_table': 'meals',
            },
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'meal_types',
            },
        ),
        migrations.CreateModel(
            name='NutritionalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('carbs', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('fats', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('protein', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='meals.Food')),
            ],
            options={
                'db_table': 'nutritional_informations',
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('meals', models.ManyToManyField(related_name='meal_plans', to='meals.Meal')),
            ],
            options={
                'db_table': 'meal_plans',
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meals', to='meals.MealType'),
        ),
        migrations.AddField(
            model_name='meal',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_meals', to='utils.Tag'),
        ),
    ]
